name: papyrus
version: 1.1.2+4
publish_to: none
description: A simple paper backup tool.
homepage: https://github.com/ooguz/papyrus
issue_tracker: https://github.com/ooguz/papyrus/issues
repository: https://github.com/ooguz/papyrus

environment: 
  sdk: '>=3.0.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  pdf: ^3.10.4
  file_picker: ^5.3.2
  auto_size_text: ^3.0.0
  printing: ^5.11.0
  crypto: ^3.0.3
  url_launcher: ^6.1.11
  about: ^2.1.3
  getx_test: ^1.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/roboto/
    - assets/courier/
    - README.md
    - CHANGELOG.md
    - LICENSE

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo.png"
  linux:
    generate: true
    image_path: "assets/logo.png"